version: 2
jobs:    
  build:
    docker:
      - image: node:11.6.0-stretch      
    branches:
      only: deploy
    steps:
      - checkout
      - run: yarn && yarn build && rm -rf docs && mv build docs && ls
      - deploy:
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "iam@aaronherres.com"
            git config user.name "Deployment Bot"
            git merge master 
            git add .
            git commit -am "Trigger deployment"           
            # Push quietly to prevent showing the token in log
            git push -q https://${GITHUB_TOKEN}@github.com/redaphid/site.git master